**Importing Libraries**

In [5]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import matplotlib.axes as ax

In [17]:
df=pd.read_csv("seeds_dataset.csv")

In [18]:
df=df[:1000]

In [19]:
df=df.drop("Unnamed: 0",axis=1)
df.head(10)


area  perimeter  compactness  ...  asymmetry  length_kernel_groove  kernel
0  15.26      14.84       0.8710  ...      2.221                 5.220       1
1  14.88      14.57       0.8811  ...      1.018                 4.956       1
2  14.29      14.09       0.9050  ...      2.699                 4.825       1
3  13.84      13.94       0.8955  ...      2.259                 4.805       1
4  16.14      14.99       0.9034  ...      1.355                 5.175       1
5  14.38      14.21       0.8951  ...      2.462                 4.956       1
6  14.69      14.49       0.8799  ...      3.586                 5.219       1
7  14.11      14.10       0.8911  ...      2.700                 5.000       1
8  16.63      15.46       0.8747  ...      2.040                 5.877       1
9  16.44      15.25       0.8880  ...      1.969                 5.533       1

[10 rows x 8 columns]

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   area                  210 non-null    float64
 1   perimeter             210 non-null    float64
 2   compactness           210 non-null    float64
 3   length                210 non-null    float64
 4   width                 210 non-null    float64
 5   asymmetry             210 non-null    float64
 6   length_kernel_groove  210 non-null    float64
 7   kernel                210 non-null    int64  
dtypes: float64(7), int64(1)
memory usage: 13.2 KB


In [22]:
df['kernel']=df['kernel']-1
df['kernel'].unique()

array([0, 1, 2])

In [23]:
df['kernel'].value_counts()

2    70
1    70
0    70
Name: kernel, dtype: int64

In [25]:
x=df.drop(df.columns[[7]],axis=1)
y=df['kernel']

In [26]:
x.head()

area  perimeter  compactness  ...  width  asymmetry  length_kernel_groove
0  15.26      14.84       0.8710  ...  3.312      2.221                 5.220
1  14.88      14.57       0.8811  ...  3.333      1.018                 4.956
2  14.29      14.09       0.9050  ...  3.337      2.699                 4.825
3  13.84      13.94       0.8955  ...  3.379      2.259                 4.805
4  16.14      14.99       0.9034  ...  3.562      1.355                 5.175

[5 rows x 7 columns]

**Spliting the Data into Train and Test**

In [72]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=0)

**Scaling**

In [73]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
xtrain=scaler.fit_transform(xtrain)
xtest=scaler.fit_transform(xtest)


In [74]:
xtrain

array([[-0.74611567, -0.65972366, -1.02218665, ..., -0.90632233,
        -0.25413579, -0.34853337],
       [ 0.6223282 ,  0.69525799,  0.18452295, ...,  0.57172364,
        -1.09659973,  0.96335943],
       [-0.43215847, -0.52346852,  0.74704923, ..., -0.25267384,
        -0.73259674, -0.45616544],
       ...,
       [ 1.48229791,  1.44466125,  0.83324277, ...,  1.50550719,
        -0.40186643,  1.58884393],
       [ 0.06266537,  0.0139823 ,  0.80148726, ...,  0.33694377,
        -0.48571355, -0.46225783],
       [-1.20681373, -1.18960475, -1.30344978, ..., -1.30117937,
         0.41331392, -0.81764674]])

In [75]:
from sklearn.linear_model import LogisticRegression

classifier=LogisticRegression()
classifier.fit(xtrain,ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [76]:
ypred=classifier.predict(xtest)

In [77]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(ytest,ypred)

In [78]:
cm

array([[16,  0,  1],
       [ 3, 18,  0],
       [ 0,  0, 15]])

In [80]:
 from sklearn.metrics import accuracy_score
 accuracy_score(ytest,ypred)

0.9245283018867925